use super::common::process_stats_subsection;
use crate::common::HiscoreName::*;
use common::source::Source;

pub fn lookup(source: Source) -> Result<Vec<String>, ()> {
    let categories = vec![
        AbyssalSire,
        AlchemicalHydra,
        Amoxliatl,
        Araxxor,
        Artio,
        BarrowsChests,
        Brutus,
        Bryophyta,
        Callisto,
        Calvarion,
        Cerberus,
        CoX,
        CoXChallenge,
        ChaosElemental,
        ChaosFanatic,
        CommanderZilyana,
        CorporealBeast,
        CrazyArchaeologist,
        DagannothPrime,
        DagannothRex,
        DagannothSupreme,
        DerangedArchaeologist,
        DoomofMokhaiotl,
        DukeSucellus,
        GeneralGraardor,
        GiantMole,
        GrotesqueGuardians,
        Hespori,
        KalphiteQueen,
        KingBlackDragon,
        Kraken,
        KreeArra,
        KrilTsutsaroth,
        LunarChests,
        Mimic,
        Nex,
        Nightmare,
        PhosanisNightmare,
        Obor,
        PhantomMuspah,
        Sarachnis,
        Scorpia,
        Scurrius,
        ShellbaneGryphon,
        Skotizo,
        SolHeredit,
        Spindel,
        Tempoross,
        Gauntlet,
        CorruptedGauntlet,
        Hueycoatl,
        RoyalTitans,
        Leviathan,
        Whisperer,
        ToB,
        ToBHard,
        ThermonuclearSmokeDevil,
        ToA,
        ToAExpert,
        TzKalZuk,
        TzTokJad,
        Vardorvis,
        Venenatis,
        Vetion,
        Vorkath,
        Wintertodt,
        Yama,
        Zalcano,
        Zulrah,
    ];

    process_stats_subsection(source, "Boss", categories)
}
